// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  // datasource: {
  //   // url: 'postgresql://postgres:root@100.111.111.46:5432/proyecto_iot?schema=public',
  //   url: 'postgresql://postgres:root@127.0.0.1:5432/datos-estacion?schema=public',
  // },
});
